service: yuavahve
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  createFamily:
    handler: src/family/create.createFamily
    events:
      - httpApi:
          path: /family/create
          method: post
  getFamily:
    handler: src/family/get.getFamily
    events:
      - httpApi:
          path: /family/{id}
          method: get
  joinFamily:
    handler: src/family/join.joinFamily
    events:
      - httpApi:
          path: /family/join
          method: post
  createUser:
    handler: src/user/create.createUser
    events:
      - httpApi:
          path: /user/create
          method: post

resources:
  Resources:
    familyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: familyTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-dynamodb-local
