service: yuavahve
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  createFamily:
    handler: src/family/create.createFamily
    events:
      - httpApi:
          path: /family/create
          method: post
  joinFamily:
    handler: src/family/join.joinFamily
    events:
      - httpApi:
          path: /family/{id}
          method: get
  createUser:
    handler: src/user/create.createUser
    events:
      - httpApi:
          path: /user/create
          method: post
  getUser:
    handler: src/user/get.getUser
    events:
      - httpApi:
          path: /user/{id}
          method: get
  createProduct:
    handler: src/product/create.createProduct
    events:
      - httpApi:
          path: /product/create
          method: post
  getProduct:
    handler: src/product/get.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get

resources:
  Resources:
    familyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: familyTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: familyId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: familyId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: productTableIndex
            KeySchema:
              - AttributeName: familyId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-dynamodb-local
