service: yuavahve
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  joinFamily:
    handler: src/family/join.joinFamily
    events:
      - httpApi:
          path: /family/{id}
          method: get
  createFamily:
    handler: src/family/create.createFamily
    events:
      - httpApi:
          path: /family/create
          method: post

resources:
  Resources:
    familyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: familyTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  tableName: familyTable
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      migrate: true
    migration:
      dir: offline/migrations
    serverless-offline:
      resourceRoutes: true

plugins:
  - serverless-offline
  - serverless-dynamodb-local
